# https://www.home-assistant.io/integrations/default_config/
default_config:

# https://www.home-assistant.io/integrations/logger/
logger:
  default: warning
  logs:
    custom_components.hass_nuki_bt: debug
    pyNukiBT : debug
debugpy: